### ISSUE TITLE
UAirship.isAppNotificationsEnabled Returning Inaccurate Values on iOS in Special Case

### ISSUE THREAD

**Issue by EthanStandel** [urbanairship/urbanairship-cordova#238]
It's my understanding that the two kinds of UrbanAirship notification state are

`UAirship.isAppNotificationsEnabled`
`UAirship.isUserNotificationsEnabled`

App & User.

App is indicative of the state of the notification switch in the general-settings-app for the device.
User is indicative of UrbanAirships intention to or not to send a notification.

The following case is the one that makes sense to me.

On iOS, if I call `UAirship.setUserNotificationsEnabled(true)` then no matter what I do in the general settings to the app notification switch for iOS, `UAirship.isUserNotificationsEnabled` always calls back true and `UAirship.isAppNotificationsEnabled` always calls back accurately to what is in the device general-settings-app.

The next case does not make sense to me.

On iOS if I call `UAirship.setUserNotificationsEnabled(false)` then no matter what I do in the general settings to the app notification switch for iOS, `UAirship.isUserNotificationsEnabled` always calls back false (expected) and `UAirship.isAppNotificationsEnabled` also always calls back false (unexpected).

What I want is for  `UAirship.isAppNotificationsEnabled` to always tell me the state of the general-settings app switch, but it only seems to do this accurately when `UAirship.isUserNotificationsEnabled`
 is true.

**Comment by BrianBatchelder** [comment]
This is a feature of the underlying iOS SDK. Could you explain to us what your use case is for having it work differently?

**Comment by EthanStandel** [comment]
The concept of "user" notifications enable-state is tied into the iOS platform?  It appears to me that only the concept of "app" notifications enable-state is tied into the iOS platform, and that the "user" notification concept is an UrbanAirship-level toggle for the channel-ID.

The use case would be that I want to be able to accurately detect what the notification toggle in general-settings app on iOS is showing for my application.

**Comment by rlepinski** [comment]
You are absolutely right that `isAppNotificationsEnabled` depends on `isUserNotificationsEnabled`. I believe this is done for historical reasons to work around a bug in iOS 9 where if you unregister for notifications, you had to restart the phone before being able to toggle them back on. Instead, the UA SDK library added checks to our notification enable toggle in our app opted in checks because we would avoid unregistering for notifications on those devices.

I need to verify the behavior on iOS 10-11 to make sure that when you disable UserNotifications, the SDK registers for 0 types, then it might turn off system notifications anyways, making the two flags interconnected. 

Another thing that you need to keep in mind is the app will not be able to receive notifications until you prompt the user for notifications. Before that app does not even have a notification settings page.

**Comment by BrianBatchelder** [comment]
Our state flags make the assumption that only the Urban Airship SDK is being used for notifications. If the app has disabled notifications in our SDK (setting `UAirship.isUserNotificationsEnabled` false), then we simplify enabled checks for the app by also reporting that notifications are not been authorized (`UAirship.isAppNotificationsEnabled` is false). We do this because Apple does not allow an app to "unrequest" authorization. The authorization is permanent, regardless of whether or not notifications are enabled in the SDK.

One option you can get around this is to create a plugin that calls [`getNotificationSettingsWithCompletionHandler:`](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649524-getnotificationsettingswithcompl) to get the current settings from the settings app.

We are currently working on this part of the iOS SDK. We will take your points under consideration, and see if we can address them in an upcoming version of our Cordova plugin.
