### ISSUE TITLE
Notification push event not called when application in background

### ISSUE THREAD

**Issue by pbirsinger** [urbanairship/urbanairship-cordova#240]
The push event listener gets called when the app is in the foreground, but never when the app is in the background. I see this warning in the xcode logs:

```
Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.
```

So why is the completion handler not getting called when the app is in the background? Here is my code adding the event listener:

```
document.addEventListener("urbanairship.push", e => { 
    console.log("received push")
}, false)
```

**Comment by crow** [comment]
Hey @pbirsinger thanks for letting us know about this, looking into it now.

**Comment by pbirsinger** [comment]
For sure. Eager to get this working!

**Comment by rlepinski** [comment]
@pbirsinger any chance you could provide verbose logs when receiving `Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.` ?

**Comment by rlepinski** [comment]
@pbirsinger It looks like cordova plugins are only loaded when the application is started in the foreground. This will prevent applications that are no longer in memory to handle the background app refresh or content-available pushes. Here[ is the line where plugins are loaded](https://github.com/apache/cordova-ios/blob/master/CordovaLib/Classes/Public/CDVViewController.m#L309), as you can see its in viewDidLoad. That will only be called if the view did actually load. A similar issue is on Android as well. Its just a limitation of the cordova framework. I do not believe this feature will work the way you want it to.

You could modify this plugin to stash received pushes in NSUserDefaults/SharedPreferences and add a new api call to fetch the received pushes. This is not a feature that we want to provide in our SDK as most use cases around it are problematic at best due to how unreliable a content-available push are.

@crow Is doing more testing to verify my above findings. The warning that is being printed is a bit concerning, so we are investigating that issue. Most likely that issue is due to receiving a BG push without an app delegate method to respond to it. Since our plugin is the one that is adding the app delegate method, and if its not getting initialized in the BG, that would explain it. We changed where our SDK is getting initialized in the master, so the issue will most likely go away with recent changes to our master branch.

**Comment by crow** [comment]
On iOS, if the view loads and you navigate away from your application after CDVViewController's ViewDidLoad is hit - then the UA plugin should be loaded and it should handle the didReceiveRemoteNotification call as long as you haven't exceeded background execution time (you have a few seconds by default). This isn't a dependable state as once background execution time has elapsed your application can be suspended at any time.

**Comment by Carlosps** [comment]
> api call to fetch the received pushes

@rlepinski  Does Urban Airship have an API call to fetch the received pushes? I was trying to use this one https://go.urbanairship.com/api/reports/responses/list? but I could not get the details of the messages, that means I could not get the title or the message itself
Not to mention the extras information that can be used when sending a message .

What should we do to somehow retrieve those messages?

Thank you.
