### ISSUE TITLE
Control playback of Notification Sound

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/urbanairship-cordova#346]
I'm trying to figure out reading the documentation and some code if it possible to stop push notification sound somehow when the notification is selected/touched or when APP is triggered/launched.

I'm using a long-play notification sound, kinda of an car alarm sound that I need to stop before it finishes playing.

thanks in advance!

**Comment by crow** [comment]
This kind of functionality isn't currently supported by Airship.  It isn't well documented because it's not directly supported on the Android and iOS native notification APIs either. It's unlikely that you're going to  have the level of control over cross-platform system notification sounds that you are looking for. Github issues also isn't a good forum for discussing potential use cases that deviate this significantly from supported functionality. Closing this for now.
